<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    تخفیف‌های فروشگاه آنلاین
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazirmatn" color="#0099cc">
        مجموعه‌داده
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazirmatn" size=3>
در این سوال قصد داریم تا سوالاتی درباره تخفیف‌هایی که یک فروشگاه آنلاین در سایت خود منتشر کرده است بپرسیم. برای حل این سوالات به ترتیب موارد خواسته شده را انجام دهید. 
<br>
دیتافریم شامل ۱۶ ستون است که در ادامه به توضیح هرکدام پرداخته شده:
    </font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    

| ستون | توضیح |
|:------:|:--------:|
| `id` | شناسه یکتای تخفیف ثبت‌شده |
| `product_variant_id` | شناسه تنوع محصول (مثل رنگ، سایز و...) که این تخفیف برای آن ثبت شده |
| `selling_price` | قیمت فروش نهایی محصول پس از اعمال تخفیف |
| `rrp_price` | قیمت پیشنهادی مصرف‌کننده یا همان قیمت روی کالا قبل از تخفیف (RRP: Recommended Retail Price) |
| `base_price` | قیمت پایه محصول در سیستم قبل از هرگونه تخفیف یا اصلاح |
| `buy_price` | قیمتی که فروشگاه محصول را خریداری کرده (قیمت تأمین) |
| `order_limit` | محدودیت در تعداد سفارش‌ها که برای این تخفیف در نظر گرفته شده (مثلاً حداکثر ۳ عدد برای هر مشتری) |
| `start_at` | زمان شروع اعمال تخفیف |
| `end_at` | زمان پایان تخفیف |
| `tags` | برچسب‌هایی برای توصیف نوع یا دسته‌بندی تخفیف (مثلاً "نوروز", "فصلی", "پیشنهاد شگفت‌انگیز") |
| `show_in_price_history` | آیا این تخفیف باید در تاریخچه قیمت محصول نمایش داده شود؟ (True/False) |
| `active` | آیا تخفیف در حال حاضر فعال است؟ (True/False) |
| `created_at` | زمان ثبت تخفیف در سیستم |
| `product_id` | شناسه کلی محصول (بدون در نظر گرفتن تنوع) |
| `marketplace_seller_id` | شناسه فروشنده‌ای که این تخفیف را ثبت کرده (برای فروشگاه‌های Marketplace) |

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
   با استفاده از سلول زیر کتابخانه‌های مورد نیاز خود را <code>import</code> کنید و سپس مجموعه‌داده را که در فایلی به نام <code>tarikhche kharid cleaned.csv</code> قرار دارد، بخوانید. دقت کنید که کاراکتر <code>N\</code> به معنای <code>Null</code> می‌باشد.
<br>
هم چنین نوع داده ستون‌های <code>['start_at','end_at','created_at']</code> را به <code>datetime</code> تغییر دهید.
   
</font>
</p>

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
# import seaborn as sns
from sklearn import tree 
from sklearn.tree import plot_tree
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import svm
from sklearn import linear_model
from sklearn import ensemble
from sklearn import neighbors
import datetime
import jdatetime

In [80]:
df = pd.read_csv("tarikhche_kharid.csv")
df

,id,product_variant_id,selling_price,rrp_price,base_price,buy_price,order_limit,start_at,end_at,tags,show_in_price_history,active,created_at,product_id,marketplace_seller_id
0,18723299,1973584,1690000,1950000,0.0,NaN,2,2018-12-01 10:00:00,2018-12-08 12:00:00,selling_and_sales,1,0,2018-11-26 13:10:31,101834,2513
1,18723298,1973450,6250000,6500000,0.0,NaN,1,2018-12-01 10:00:00,2018-12-08 12:00:00,selling_and_sales,1,0,2018-11-26 13:10:31,21040,2513
2,18731279,1969409,490000,520000,0.0,NaN,1,2018-11-29 12:55:00,2018-12-07 12:57:00,selling_and_sales,1,0,2018-11-26 14:43:55,711229,915
3,18689235,1968436,590000,710000,0.0,NaN,3,2018-11-26 00:00:00,2018-11-27 00:00:00,incredible_offer,1,0,2018-11-26 03:49:37,362394,63352
4,18685904,1968256,826500,870000,0.0,NaN,10,2018-11-27 00:00:00,2018-11-28 00:00:00,incredible_offer,1,0,2018-11-26 01:24:15,189452,61521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57196,9755344,1155147,1079100,1380000,NaN,NaN,2,2018-07-28 00:00:00,2018-08-03 00:00:00,sponsored_offer,0,0,2018-07-28 16:58:51,87150,2108
57197,13844769,1155143,1871100,2500000,0.0,NaN,2,2018-10-01 21:00:48,2018-10-03 00:00:50,selling_and_sales,1,0,2018-10-01 18:46:48,483222,3937
57198,14302539,1155117,8633000,8900000,0.0,NaN,2,2018-10-08 00:00:21,2018-10-09 00:00:05,incredible_offer,1,0,2018-10-07 08:53:29,56307,8776
57199,15952720,1155093,2330000,2420000,0.0,NaN,5,2018-11-19 10:00:00,2018-11-27 10:00:00,selling_and_sales,1,1,2018-10-24 16:26:50,390295,2009
57200,13668716,1155078,218000,369000,0.0,NaN,1,2018-10-08 12:00:18,2018-10-13 15:12:44,selling_and_sales,1,0,2018-09-29 12:34:41,169329,7664

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57201 entries, 0 to 57200
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     57201 non-null  int64
 1   product_variant_id     57201 non-null  int64
 2   selling_price          57201 non-null  int64
 3   rrp_price              57201 non-null  int64
 4   base_price             53165 non-null  float64
 5   buy_price              3974 non-null   float64
 6   order_limit            57201 non-null  int64
 7   start_at               57201 non-null  str
 8   end_at                 57201 non-null  str
 9   tags                   57201 non-null  str
 10  show_in_price_history  57201 non-null  int64
 11  active                 57201 non-null  int64
 12  created_at             57201 non-null  str
 13  product_id             57201 non-null  int64
 14  marketplace_seller_id  57201 non-null  int64
dtypes: float64(2), int64(9), str(4)
memory usage: 6.5 MB

In [82]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,57201.0,1.429734e+07,2.488699e+06,8845579.0,12075918.0,14485825.0,16459805.0,18750660.0
product_variant_id,57201.0,1.460903e+06,1.942999e+05,1155078.0,1294919.0,1452587.0,1614193.0,1973584.0
selling_price,57201.0,2.771129e+06,8.406025e+06,1.0,350000.0,890000.0,2552640.0,390000000.0
rrp_price,57201.0,3.170236e+06,8.876027e+06,11000.0,450000.0,1100000.0,3000000.0,400000000.0
base_price,53165.0,3.492907e+05,3.769296e+06,0.0,0.0,0.0,0.0,393000000.0
buy_price,3974.0,3.613043e+06,1.226226e+07,29975.0,427324.0,921744.0,2703200.0,361928583.0
order_limit,57201.0,7.304156e+00,5.109827e+01,1.0,1.0,1.0,3.0,10000.0
show_in_price_history,57201.0,9.293544e-01,2.562342e-01,0.0,1.0,1.0,1.0,1.0
active,57201.0,1.681789e-02,1.285898e-01,0.0,0.0,0.0,0.0,1.0
product_id,57201.0,4.511711e+05,2.368487e+05,300.0,227199.0,469838.0,654743.0,938764.0
marketplace_seller_id,57201.0,2.087368e+04,2.657838e+04,1.0,2125.0,8885.0,46654.0,87999.0

In [83]:
df.isnull().sum()

id                           0
product_variant_id           0
selling_price                0
rrp_price                    0
base_price                4036
buy_price                53227
order_limit                  0
start_at                     0
end_at                       0
tags                         0
show_in_price_history        0
active                       0
created_at                   0
product_id                   0
marketplace_seller_id        0
dtype: int64

In [84]:
df["base_price"] = df["base_price"].fillna(df["base_price"].mean())
df["buy_price"] = df["buy_price"].fillna(df["buy_price"].mean())

In [85]:
LE = preprocessing.LabelEncoder()
df["tags"] = LE.fit_transform(df["tags"])

In [86]:
df2 = df.drop(["start_at", "end_at", "created_at", "id"], axis=1)
df2

,product_variant_id,selling_price,rrp_price,base_price,buy_price,order_limit,tags,show_in_price_history,active,product_id,marketplace_seller_id
0,1973584,1690000,1950000,0.00000,3.613043e+06,2,1,1,0,101834,2513
1,1973450,6250000,6500000,0.00000,3.613043e+06,1,1,1,0,21040,2513
2,1969409,490000,520000,0.00000,3.613043e+06,1,1,1,0,711229,915
3,1968436,590000,710000,0.00000,3.613043e+06,3,0,1,0,362394,63352
4,1968256,826500,870000,0.00000,3.613043e+06,10,0,1,0,189452,61521
...,...,...,...,...,...,...,...,...,...,...,...
57196,1155147,1079100,1380000,349290.69794,3.613043e+06,2,2,0,0,87150,2108
57197,1155143,1871100,2500000,0.00000,3.613043e+06,2,1,1,0,483222,3937
57198,1155117,8633000,8900000,0.00000,3.613043e+06,2,0,1,0,56307,8776
57199,1155093,2330000,2420000,0.00000,3.613043e+06,5,1,1,1,390295,2009
57200,1155078,218000,369000,0.00000,3.613043e+06,1,1,1,0,169329,7664

In [87]:
x = df2.drop(columns=["selling_price"])
y = df2["selling_price"]

In [88]:
x_train,x_test,y_train,y_test=train_test_split(x, y, random_state=42, test_size=0.2)

In [89]:
model_forest=ensemble.RandomForestRegressor()
model_forest.fit(x,y)
y_forest=model_forest.predict(x)
metrics.r2_score(y,y_forest,multioutput='variance_weighted')*100

99.82008683158521

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
حالا تعداد مقادیر خالی دیتافریم را به کمک توابع پانداز پیدا کنید و در متغیر <code>ٔnull_count</code> بریزید. برای ساده‌سازی دیتافریم ستون‌هایی که دارای مقادیر خالی هستند را از دیتافریم حذف کنید. 
</font>
</p>

In [90]:
# نمایش تعداد داده‌های خالی در هر ستون
null_count = None 

# # حذف ستون‌های با مقادیر زیاد ۰ یا خالی 
# df.drop(columns=['buy_price', 'base_price'], inplace=True)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
به کمک کتابخانه‌هایی که می‌شناسید ستون‌هایی که تاریخ هستند را با فرمت <code>'%Y-%m-%d'</code> به تاریخ شمسی تبدیل کنید و در ستون‌هایی با نام‌های <code>['start_at_jalali','end_at_jalali','created_at_jalali']</code> به دیتافریم اضافه کنید.
</font>
</p>

In [92]:
df["start_at"] = pd.to_datetime(df["start_at"],format="%Y-%m-%d %H:%M:%S")
df["start_at_jalali"] = df["start_at"].apply(lambda x: jdatetime.datetime.fromgregorian(datetime=x).strftime("%Y-%m-%d %H:%M:%S"))

df["end_at"] = pd.to_datetime(df["end_at"],format="%Y-%m-%d %H:%M:%S")
df["end_at_jalali"] = df["end_at"].apply(lambda x: jdatetime.datetime.fromgregorian(datetime=x).strftime("%Y-%m-%d %H:%M:%S"))

df["created_at"] = pd.to_datetime(df["created_at"],format="%Y-%m-%d %H:%M:%S")
df["created_at_jalali"] = df["created_at"].apply(lambda x: jdatetime.datetime.fromgregorian(datetime=x).strftime("%Y-%m-%d %H:%M:%S"))

# تبدیل ستون‌های تاریخی به شمسی

# نمایش نمونه‌ای از ستون‌های جدید
df[['created_at', 'created_at_jalali']].head()

           created_at    created_at_jalali
0 2018-11-26 13:10:31  1397-09-05 13:10:31
1 2018-11-26 13:10:31  1397-09-05 13:10:31
2 2018-11-26 14:43:55  1397-09-05 14:43:55
3 2018-11-26 03:49:37  1397-09-05 03:49:37
4 2018-11-26 01:24:15  1397-09-05 01:24:15

In [93]:
df[['created_at', 'created_at_jalali']].info()

<class 'pandas.DataFrame'>
RangeIndex: 57201 entries, 0 to 57200
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   created_at         57201 non-null  datetime64[us]
 1   created_at_jalali  57201 non-null  str
dtypes: datetime64[us](1), str(1)
memory usage: 893.9 KB

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazirmatn" color="#0099cc">
سوال اول
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazirmatn" size=3>
    مقدار میانگین و میانه درصد تخفیف‌ها را محاسبه کنید. 
    <br>
    برای محاسبه درصد تخفیف باید ابتدا اختلاف مقدار پیشنهادی و مقدار فروش را به دست آورید و در ستون <code>discount_amount</code> بریزید.
    سپس این مقدار را بر مقدار قیمت پیشنهادی تقسیم و نهایتا در ۱۰۰ ضرب کنید و در ستون <code>discount_percent</code> بریزید.
    این ستون همان مقدار درصد تخفیف خواهد بود. 
</font>
    </p>

In [96]:

df['discount_amount'] = df["rrp_price"] - df["selling_price"]
df['discount_percent'] = df["discount_amount"] / df["rrp_price"] *100

discount_percent_mean = df["discount_percent"].mean()
discount_percent_median = df["discount_percent"].median()

print("میانگین درصد تخفیف:", discount_percent_mean)
print("میانه درصد تخفیف:", discount_percent_median)

میانگین درصد تخفیف: 16.80552511272506
میانه درصد تخفیف: 12.258064516129032

In [97]:
df

,id,product_variant_id,selling_price,rrp_price,base_price,buy_price,order_limit,start_at,end_at,tags,show_in_price_history,active,created_at,product_id,marketplace_seller_id,start_at_jalali,end_at_jalali,created_at_jalali,discount_amount,discount_percent
0,18723299,1973584,1690000,1950000,0.00000,3.613043e+06,2,2018-12-01 10:00:00,2018-12-08 12:00:00,1,1,0,2018-11-26 13:10:31,101834,2513,1397-09-10 10:00:00,1397-09-17 12:00:00,1397-09-05 13:10:31,260000,13.333333
1,18723298,1973450,6250000,6500000,0.00000,3.613043e+06,1,2018-12-01 10:00:00,2018-12-08 12:00:00,1,1,0,2018-11-26 13:10:31,21040,2513,1397-09-10 10:00:00,1397-09-17 12:00:00,1397-09-05 13:10:31,250000,3.846154
2,18731279,1969409,490000,520000,0.00000,3.613043e+06,1,2018-11-29 12:55:00,2018-12-07 12:57:00,1,1,0,2018-11-26 14:43:55,711229,915,1397-09-08 12:55:00,1397-09-16 12:57:00,1397-09-05 14:43:55,30000,5.769231
3,18689235,1968436,590000,710000,0.00000,3.613043e+06,3,2018-11-26 00:00:00,2018-11-27 00:00:00,0,1,0,2018-11-26 03:49:37,362394,63352,1397-09-05 00:00:00,1397-09-06 00:00:00,1397-09-05 03:49:37,120000,16.901408
4,18685904,1968256,826500,870000,0.00000,3.613043e+06,10,2018-11-27 00:00:00,2018-11-28 00:00:00,0,1,0,2018-11-26 01:24:15,189452,61521,1397-09-06 00:00:00,1397-09-07 00:00:00,1397-09-05 01:24:15,43500,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57196,9755344,1155147,1079100,1380000,349290.69794,3.613043e+06,2,2018-07-28 00:00:00,2018-08-03 00:00:00,2,0,0,2018-07-28 16:58:51,87150,2108,1397-05-06 00:00:00,1397-05-12 00:00:00,1397-05-06 16:58:51,300900,21.804348
57197,13844769,1155143,1871100,2500000,0.00000,3.613043e+06,2,2018-10-01 21:00:48,2018-10-03 00:00:50,1,1,0,2018-10-01 18:46:48,483222,3937,1397-07-09 21:00:48,1397-07-11 00:00:50,1397-07-09 18:46:48,628900,25.156000
57198,14302539,1155117,8633000,8900000,0.00000,3.613043e+06,2,2018-10-08 00:00:21,2018-10-09 00:00:05,0,1,0,2018-10-07 08:53:29,56307,8776,1397-07-16 00:00:21,1397-07-17 00:00:05,1397-07-15 08:53:29,267000,3.000000
57199,15952720,1155093,2330000,2420000,0.00000,3.613043e+06,5,2018-11-19 10:00:00,2018-11-27 10:00:00,1,1,1,2018-10-24 16:26:50,390295,2009,1397-08-28 10:00:00,1397-09-06 10:00:00,1397-08-02 16:26:50,90000,3.719008
57200,13668716,1155078,218000,369000,0.00000,3.613043e+06,1,2018-10-08 12:00:18,2018-10-13 15:12:44,1,1,0,2018-09-29 12:34:41,169329,7664,1397-07-16 12:00:18,1397-07-21 15:12:44,1397-07-07 12:34:41,151000,40.921409

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazirmatn" color="#0099cc">
سوال دوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazirmatn" size=3>
بهترین روز برای خرید چه روزی از هفته است. یعنی در چه روزی از هفته با احتمال بیشتری می‌توانیم محصول مورد نظر خود را با تخفیف بیشتری خرید کنیم؟ 
    <br> ابتدا نام روز‌های هفته را بر اساس روز شروع تخفیف پیدا کنید و در ستونی با اسم <code>day_of_week</code> به دیتافریم اضافه کنید. <br>
    منظور از بهترین روز، روزی است که در آن بیشترین مقدار تخفیف وجود داشته باشد. برای محاسبه این مقدار باید ابتدا میانگین درصد تخفیف‌ها را برای هر روز از هفته محاسبه کنید. سپس تعداد تخفیف‌ها را برای روزهای هفته محاسبه کنید و این دو مقدار را در یکدیگر ضرب کنید. در نهایت با مقایسه اعداد به دست آمده بزرگترین عدد را به عنوان بهترین روز برای خرید انتخاب کنید. <br> خروجی خود را در متغیر <code>best_day</code> به صورت یک تاپل دو عضوی که عضو اول آن مقدار بهترین روز و مقدار دوم آن نام بهترین روز است ذخیره کنید. <br> مثال: <code>('یکشنبه', 78765.92767584008)</code> <br>راهنمایی: این مقدار برای روز یکشنبه به صورت دقیق محاسبه شده و می‌توانید از آن برای اطمینان از محاسبات خود استفاده کنید. 
    </font>
    </p>

In [101]:
# تبدیل نام روزها به زبان فارسی
day_names_fa = {
    'Monday': 'دوشنبه',
    'Tuesday': 'سه‌شنبه',
    'Wednesday': 'چهارشنبه',
    'Thursday': 'پنج‌شنبه',
    'Friday': 'جمعه',
    'Saturday': 'شنبه',
    'Sunday': 'یکشنبه'
}
df["day_of_week"] = df["start_at"].dt.day_name()

df["day_of_week"] = df["day_of_week"].apply(lambda x: day_names_fa[x])

df["day_of_week"]

0            شنبه
1            شنبه
2        پنج‌شنبه
3          دوشنبه
4         سه‌شنبه
           ...
57196        شنبه
57197      دوشنبه
57198      دوشنبه
57199      دوشنبه
57200      دوشنبه
Name: day_of_week, Length: 57201, dtype: str

In [122]:
result1 = df[['discount_percent',"day_of_week"]].groupby("day_of_week").mean(numeric_only=True)
result1.index.name = None
result1
result1_percent = result1["discount_percent"]
result1_percent

جمعه        19.044414
دوشنبه      17.438747
سه‌شنبه     14.547678
شنبه        17.511192
پنج‌شنبه    14.106325
چهارشنبه    15.204465
یکشنبه      18.669336
Name: discount_percent, dtype: float64

In [123]:
result2 = df[['discount_percent',"day_of_week"]].groupby("day_of_week").count()
result2.index.name = None
result2
result2_percent = result2["discount_percent"]
result2_percent

جمعه         2201
دوشنبه       9374
سه‌شنبه      7041
شنبه        25146
پنج‌شنبه     5293
چهارشنبه     3927
یکشنبه       4219
Name: discount_percent, dtype: int64

In [125]:
result = result1_percent * result2_percent
result_max = max(result)
result_max

440336.42842713284

In [139]:

# محاسبه میانگین تخفیف‌ها بر اساس روز هفته
mean_discount_by_day = df[['discount_percent',"day_of_week"]].groupby("day_of_week").mean(numeric_only=True)
mean_discount_by_day.index.name = None
mean_discount_by_day = mean_discount_by_day["discount_percent"]

print("میانگین تخفیف‌ها بر اساس روز هفته:")
print(mean_discount_by_day)


# محاسبه تعداد تخفیف‌ها بر اساس روز هفته
count_discount_by_day = df[['discount_percent',"day_of_week"]].groupby("day_of_week").count()
count_discount_by_day.index.name = None
count_discount_by_day = count_discount_by_day["discount_percent"]
 
print(" تعداد تخفیف‌ها بر اساس روز هفته:")
print(count_discount_by_day)

میانگین تخفیف‌ها بر اساس روز هفته:
جمعه        19.044414
دوشنبه      17.438747
سه‌شنبه     14.547678
شنبه        17.511192
پنج‌شنبه    14.106325
چهارشنبه    15.204465
یکشنبه      18.669336
Name: discount_percent, dtype: float64
 تعداد تخفیف‌ها بر اساس روز هفته:
جمعه         2201
دوشنبه       9374
سه‌شنبه      7041
شنبه        25146
پنج‌شنبه     5293
چهارشنبه     3927
یکشنبه       4219
Name: discount_percent, dtype: int64

In [145]:
result = mean_discount_by_day * count_discount_by_day
result_max = max(result)
print(result_max)
print("-----------------------")
print(result)

440336.42842713284
-----------------------
جمعه         41916.754980
دوشنبه      163470.811311
سه‌شنبه     102430.203208
شنبه        440336.428427
پنج‌شنبه     74664.780608
چهارشنبه     59707.935763
یکشنبه       78765.927676
Name: discount_percent, dtype: float64

In [146]:

# پیدا کردن روزی که بیشترین تخفیف را داشته است
best_day = ("شنبه",result_max)
print("روز با بیشترین تخفیف:")
print(best_day)

روز با بیشترین تخفیف:
('شنبه', 440336.42842713284)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazirmatn" color="#0099cc">
سوال سوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazirmatn" size=3>تاریخ شمسی ده روزی که بیشترین تعداد تخفیف در آنها ایجاد شده را به صورت یک لیست  در متغیر <code>most_daily_discount</code> ذخیره کنید.
</font>
    </p>

In [161]:
result3 = df[["start_at_jalali","id"]].groupby("start_at_jalali").count()
result3.index.name = None
result3

                       id
1397-02-26 09:52:00     1
1397-04-06 07:00:00     8
1397-04-23 10:00:00    18
1397-04-24 00:00:00   121
1397-04-26 00:00:00   113
...                   ...
1397-09-13 23:47:00     3
1397-09-14 00:56:00     2
1397-09-20 09:20:00     2
1397-09-26 00:00:00     3
1397-09-27 00:00:00  1519

[815 rows x 1 columns]

In [162]:
most_daily_discount = result3.sort_values(by="id")

most_daily_discount = list(result.index[:10])

print(most_daily_discount)

['1397-02-26 09:52:00', '1397-09-03 14:02:00', '1397-09-03 17:39:00', '1397-09-03 22:02:00', '1397-09-05 09:24:00', '1397-07-17 00:00:06', '1397-07-17 10:07:00', '1397-04-28 07:00:00', '1397-05-01 07:00:00', '1397-07-14 15:55:28']

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazirmatn" color="#0099cc">
سوال چهارم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazirmatn" size=3>مدت زمان متوسط تخفیف‌ها چند روز است؟  جواب خود را تا یک رقم اعشار در متغیر <code>duration_mean</code> ذخیره کنید.
</font>
    </p>

In [164]:
duration_mean = None

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) در غیر این صورت، در پایان مسابقه نمره شما به صفر تغییر خواهد کرد.
    <br>
    همچنین اگر از کولب برای اجرای این فایل نوت‌بوک استفاده می‌کنید، قبل از ارسال فایل <code>result.zip</code>، آخرین نسخه‌ی نوت‌بوک خود را دانلود کرده و داخل فایل ارسالی قرار دهید.
</font>

In [165]:
import joblib
import zipfile

joblib.dump(discount_percent_mean, 'discount_percent_mean')
joblib.dump(discount_percent_median, 'discount_percent_median')
joblib.dump(best_day, 'best_day')
joblib.dump(most_daily_discount, 'most_daily_discount')
joblib.dump(duration_mean, 'duration_mean')
df.to_csv('df.csv', index=False)


def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['Online Store Discounts.ipynb','discount_percent_mean','discount_percent_median','best_day','most_daily_discount','duration_mean','df.csv']
compress(file_names)

File Paths:
['Online Store Discounts.ipynb', 'discount_percent_mean', 'discount_percent_median', 'best_day', 'most_daily_discount', 'duration_mean', 'df.csv']